-- MySQL Script generated by MySQL Workbench
-- wto, 25 gru 2018, 20:29:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema MovieBookDataBase
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema MovieBookDataBase
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MovieBookDataBase` DEFAULT CHARACTER SET utf8 ;
USE `MovieBookDataBase` ;

-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Cinema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Cinema` (
  `idCinema` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCinema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Movie` (
  `idMovie` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `language` VARCHAR(45) NOT NULL,
  `dateOfPremiere` DATE NOT NULL,
  `boxOffice` INT NULL,
  `country` VARCHAR(45) NULL,
  `description` VARCHAR(256) NULL,
  `pictureUrl` VARCHAR(256) NULL,
  PRIMARY KEY (`idMovie`),
  INDEX `title` (`title` ASC))
ENGINE = InnoDB PARTITION BY KEY(idMovie) PARTITIONS 8 ;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Show`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Show` (
  `idShow` INT NOT NULL AUTO_INCREMENT,
  `dateTime` DATETIME NOT NULL,
  `Cinema_idCinema` INT NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  PRIMARY KEY (`idShow`),
  INDEX `fk_Show_Cinema_idx` (`Cinema_idCinema` ASC),
  INDEX `fk_Show_Movie1_idx` (`Movie_idMovie` ASC),
  INDEX `date` (`dateTime` ASC),
  CONSTRAINT `fk_Show_Cinema`
    FOREIGN KEY (`Cinema_idCinema`)
    REFERENCES `MovieBookDataBase`.`Cinema` (`idCinema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Show_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `MovieBookDataBase`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Artist` (
  `idArtist` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `origin` VARCHAR(45) NULL,
  `birthDate` DATE NULL,
  PRIMARY KEY (`idArtist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`ArtistType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`ArtistType` (
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Artist_has_ArtistType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Artist_has_ArtistType` (
  `Artist_idArtist` INT NOT NULL,
  `ArtistType_name` VARCHAR(64) NOT NULL,
  INDEX `fk_Artist_has_ArtistType_ArtistType1_idx` (`ArtistType_name` ASC),
  INDEX `fk_Artist_has_ArtistType_Artist1_idx` (`Artist_idArtist` ASC),
  CONSTRAINT `fk_Artist_has_ArtistType_Artist1`
    FOREIGN KEY (`Artist_idArtist`)
    REFERENCES `MovieBookDataBase`.`Artist` (`idArtist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artist_has_ArtistType_ArtistType1`
    FOREIGN KEY (`ArtistType_name`)
    REFERENCES `MovieBookDataBase`.`ArtistType` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Genre` (
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Movie_has_Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Movie_has_Genre` (
  `Movie_idMovie` INT NOT NULL,
  `Genre_name` VARCHAR(32) NOT NULL,
  INDEX `fk_Movie_has_Genre_Genre1_idx` (`Genre_name` ASC),
  INDEX `fk_Movie_has_Genre_Movie1_idx` (`Movie_idMovie` ASC),
  CONSTRAINT `fk_Movie_has_Genre_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `MovieBookDataBase`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Genre_Genre1`
    FOREIGN KEY (`Genre_name`)
    REFERENCES `MovieBookDataBase`.`Genre` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Prize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Prize` (
  `idPrize` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `whatFor` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `Artist_idArtist` INT NULL,
  `Movie_idMovie` INT NULL,
  PRIMARY KEY (`idPrize`),
  INDEX `fk_Price_Artist1_idx` (`Artist_idArtist` ASC),
  INDEX `fk_Price_Movie1_idx` (`Movie_idMovie` ASC),
  CONSTRAINT `fk_Price_Artist1`
    FOREIGN KEY (`Artist_idArtist`)
    REFERENCES `MovieBookDataBase`.`Artist` (`idArtist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Price_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `MovieBookDataBase`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`TvProgram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`TvProgram` (
  `idTvProgram` INT NOT NULL AUTO_INCREMENT,
  `station` VARCHAR(45) NOT NULL,
  `dateTime` DATETIME NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  PRIMARY KEY (`idTvProgram`),
  INDEX `fk_ProgramTV_Movie1_idx` (`Movie_idMovie` ASC),
  INDEX `station` (`station` ASC),
  CONSTRAINT `fk_ProgramTV_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `MovieBookDataBase`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`UserType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`UserType` (
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`User` (
  `login` VARCHAR(32) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `UserType_name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`login`),
  INDEX `fk_User_UserType1_idx` (`UserType_name` ASC),
  CONSTRAINT `fk_User_UserType1`
    FOREIGN KEY (`UserType_name`)
    REFERENCES `MovieBookDataBase`.`UserType` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB PARTITION BY KEY(login) PARTITIONS 8 ;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Quiz` (
  `idQuiz` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idQuiz`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`QuizScore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`QuizScore` (
  `score` INT NOT NULL,
  `dateTime` DATETIME NULL,
  `User_login` VARCHAR(32) NOT NULL,
  `Quiz_idQuiz` INT NOT NULL,
  INDEX `fk_QuizScore_User1_idx` (`User_login` ASC),
  INDEX `fk_QuizScore_Quiz1_idx` (`Quiz_idQuiz` ASC),
  CONSTRAINT `fk_QuizScore_User1`
    FOREIGN KEY (`User_login`)
    REFERENCES `MovieBookDataBase`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QuizScore_Quiz1`
    FOREIGN KEY (`Quiz_idQuiz`)
    REFERENCES `MovieBookDataBase`.`Quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Answer` (
  `idAnswer` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(256) NULL,
  PRIMARY KEY (`idAnswer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Question` (
  `idQuestion` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(1024) NOT NULL,
  `rightAnswer_idAnswer` INT NOT NULL,
  PRIMARY KEY (`idQuestion`),
  INDEX `fk_Question_1_idx` (`rightAnswer_idAnswer` ASC),
  CONSTRAINT `fk_Question_1`
    FOREIGN KEY (`rightAnswer_idAnswer`)
    REFERENCES `MovieBookDataBase`.`Answer` (`idAnswer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Quiz_has_Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Quiz_has_Question` (
  `Question_idQuestion` INT NOT NULL,
  `Quiz_idQuiz` INT NOT NULL,
  INDEX `fk_Question_has_Quiz_Quiz1_idx` (`Quiz_idQuiz` ASC),
  INDEX `fk_Question_has_Quiz_Question1_idx` (`Question_idQuestion` ASC),
  CONSTRAINT `fk_Question_has_Quiz_Question1`
    FOREIGN KEY (`Question_idQuestion`)
    REFERENCES `MovieBookDataBase`.`Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Question_has_Quiz_Quiz1`
    FOREIGN KEY (`Quiz_idQuiz`)
    REFERENCES `MovieBookDataBase`.`Quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Answer_has_Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Answer_has_Question` (
  `Answer_idAnswer` INT NOT NULL,
  `Question_idQuestion` INT NOT NULL,
  INDEX `fk_Answer_has_Question_Question1_idx` (`Question_idQuestion` ASC),
  INDEX `fk_Answer_has_Question_Answer1_idx` (`Answer_idAnswer` ASC),
  CONSTRAINT `fk_Answer_has_Question_Answer1`
    FOREIGN KEY (`Answer_idAnswer`)
    REFERENCES `MovieBookDataBase`.`Answer` (`idAnswer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Answer_has_Question_Question1`
    FOREIGN KEY (`Question_idQuestion`)
    REFERENCES `MovieBookDataBase`.`Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Issue` (
  `idIssue` INT NOT NULL AUTO_INCREMENT,
  `dateTime` DATETIME NOT NULL,
  `desprition` VARCHAR(256) NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  `User_login` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idIssue`),
  INDEX `fk_Issue_Movie1_idx` (`Movie_idMovie` ASC),
  INDEX `fk_Issue_User1_idx` (`User_login` ASC),
  INDEX `date` (`dateTime` ASC),
  CONSTRAINT `fk_Issue_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `MovieBookDataBase`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Issue_User1`
    FOREIGN KEY (`User_login`)
    REFERENCES `MovieBookDataBase`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Review` (
  `idReview` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(1024) NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  `User_login` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idReview`),
  INDEX `fk_Review_Movie1_idx` (`Movie_idMovie` ASC),
  INDEX `fk_Review_User1_idx` (`User_login` ASC),
  CONSTRAINT `fk_Review_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `MovieBookDataBase`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_User1`
    FOREIGN KEY (`User_login`)
    REFERENCES `MovieBookDataBase`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Like` (
  `Review_idReview` INT NOT NULL,
  `User_login` VARCHAR(32) NOT NULL,
  INDEX `fk_Like_Review1_idx` (`Review_idReview` ASC),
  INDEX `fk_Like_User1_idx` (`User_login` ASC),
  CONSTRAINT `fk_Like_Review1`
    FOREIGN KEY (`Review_idReview`)
    REFERENCES `MovieBookDataBase`.`Review` (`idReview`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Like_User1`
    FOREIGN KEY (`User_login`)
    REFERENCES `MovieBookDataBase`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`ToWatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`ToWatch` (
  `User_login` VARCHAR(32) NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  INDEX `fk_towatch_User1_idx` (`User_login` ASC),
  INDEX `fk_towatch_Movie1_idx` (`Movie_idMovie` ASC),
  CONSTRAINT `fk_towatch_User1`
    FOREIGN KEY (`User_login`)
    REFERENCES `MovieBookDataBase`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_towatch_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `MovieBookDataBase`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Movie_has_Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Movie_has_Artist` (
  `Movie_idMovie` INT NOT NULL,
  `Artist_idArtist` INT NOT NULL,
  `ArtistType_name` VARCHAR(64) NOT NULL,
  INDEX `fk_Movie_has_Artist_Artist1_idx` (`Artist_idArtist` ASC),
  INDEX `fk_Movie_has_Artist_Movie1_idx` (`Movie_idMovie` ASC),
  INDEX `fk_Movie_has_Artist_ArtistType1_idx` (`ArtistType_name` ASC),
  CONSTRAINT `fk_Movie_has_Artist_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `MovieBookDataBase`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Artist_Artist1`
    FOREIGN KEY (`Artist_idArtist`)
    REFERENCES `MovieBookDataBase`.`Artist` (`idArtist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Artist_ArtistType1`
    FOREIGN KEY (`ArtistType_name`)
    REFERENCES `MovieBookDataBase`.`ArtistType` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MovieBookDataBase`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MovieBookDataBase`.`Rating` (
  `User_login` VARCHAR(32) NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  `rate` INT NOT NULL,
  PRIMARY KEY (`User_login`, `Movie_idMovie`),
  INDEX `fk_User_has_Movie_Movie1_idx` (`Movie_idMovie` ASC),
  INDEX `fk_User_has_Movie_User1_idx` (`User_login` ASC),
  CONSTRAINT `fk_User_has_Movie_User1`
    FOREIGN KEY (`User_login`)
    REFERENCES `MovieBookDataBase`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Movie_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `MovieBookDataBase`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
