-- MySQL Script generated by MySQL Workbench
-- sob, 19 sty 2019, 13:06:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema 29209262_bd2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 29209262_bd2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `29209262_bd2` DEFAULT CHARACTER SET utf8 ;
USE `29209262_bd2` ;

-- -----------------------------------------------------
-- Table `29209262_bd2`.`Cinema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Cinema` (
  `idCinema` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCinema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Movie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Movie` (
  `idMovie` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `language` VARCHAR(45) NOT NULL,
  `dateOfPremiere` DATE NOT NULL,
  `boxOffice` INT NULL,
  `country` VARCHAR(45) NULL,
  `description` VARCHAR(256) NULL,
  `pictureUrl` VARCHAR(256) NULL,
  PRIMARY KEY (`idMovie`),
  INDEX `title` (`title` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Show`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Show` (
  `idShow` INT NOT NULL AUTO_INCREMENT,
  `dateTime` DATETIME NOT NULL,
  `Cinema_idCinema` INT NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  PRIMARY KEY (`idShow`),
  INDEX `fk_Show_Cinema_idx` (`Cinema_idCinema` ASC),
  INDEX `fk_Show_Movie1_idx` (`Movie_idMovie` ASC),
  INDEX `date` (`dateTime` ASC),
  CONSTRAINT `fk_Show_Cinema`
    FOREIGN KEY (`Cinema_idCinema`)
    REFERENCES `29209262_bd2`.`Cinema` (`idCinema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Show_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `29209262_bd2`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Artist` (
  `idArtist` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `origin` VARCHAR(45) NULL,
  `birthDate` DATE NULL,
  `pictureUrl` VARCHAR(256) NULL,
  PRIMARY KEY (`idArtist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`ArtistType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`ArtistType` (
  `name` VARCHAR(64) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Artist_has_ArtistType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Artist_has_ArtistType` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Artist_idArtist` INT NOT NULL,
  `ArtistType_name` VARCHAR(64) NOT NULL,
  INDEX `fk_Artist_has_ArtistType_ArtistType1_idx` (`ArtistType_name` ASC),
  INDEX `fk_Artist_has_ArtistType_Artist1_idx` (`Artist_idArtist` ASC),
  PRIMARY KEY (`id`, `Artist_idArtist`, `ArtistType_name`),
  CONSTRAINT `fk_Artist_has_ArtistType_Artist1`
    FOREIGN KEY (`Artist_idArtist`)
    REFERENCES `29209262_bd2`.`Artist` (`idArtist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Artist_has_ArtistType_ArtistType1`
    FOREIGN KEY (`ArtistType_name`)
    REFERENCES `29209262_bd2`.`ArtistType` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Genre` (
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Movie_has_Genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Movie_has_Genre` (
  `Movie_idMovie` INT NOT NULL,
  `Genre_name` VARCHAR(32) NOT NULL,
  INDEX `fk_Movie_has_Genre_Genre1_idx` (`Genre_name` ASC),
  INDEX `fk_Movie_has_Genre_Movie1_idx` (`Movie_idMovie` ASC),
  PRIMARY KEY (`Movie_idMovie`, `Genre_name`),
  CONSTRAINT `fk_Movie_has_Genre_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `29209262_bd2`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Genre_Genre1`
    FOREIGN KEY (`Genre_name`)
    REFERENCES `29209262_bd2`.`Genre` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Prize`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Prize` (
  `idPrize` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `whatFor` VARCHAR(45) NOT NULL,
  `date` YEAR NOT NULL,
  `Artist_idArtist` INT NULL,
  `Movie_idMovie` INT NULL,
  PRIMARY KEY (`idPrize`),
  INDEX `fk_Price_Artist1_idx` (`Artist_idArtist` ASC),
  INDEX `fk_Price_Movie1_idx` (`Movie_idMovie` ASC),
  CONSTRAINT `fk_Price_Artist1`
    FOREIGN KEY (`Artist_idArtist`)
    REFERENCES `29209262_bd2`.`Artist` (`idArtist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Price_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `29209262_bd2`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Station` (
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`TvProgram`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`TvProgram` (
  `idTvProgram` INT NOT NULL AUTO_INCREMENT,
  `Station_name` VARCHAR(45) NOT NULL,
  `dateTime` DATETIME NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  PRIMARY KEY (`idTvProgram`),
  INDEX `fk_ProgramTV_Movie1_idx` (`Movie_idMovie` ASC),
  INDEX `station` (`Station_name` ASC),
  CONSTRAINT `fk_ProgramTV_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `29209262_bd2`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TvProgram_1`
    FOREIGN KEY (`Station_name`)
    REFERENCES `29209262_bd2`.`Station` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`UserType`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`UserType` (
  `name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`User` (
  `login` VARCHAR(32) NOT NULL,
  `password` VARCHAR(256) NOT NULL,
  `UserType_name` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`login`),
  INDEX `fk_User_UserType1_idx` (`UserType_name` ASC),
  CONSTRAINT `fk_User_UserType1`
    FOREIGN KEY (`UserType_name`)
    REFERENCES `29209262_bd2`.`UserType` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Quiz`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Quiz` (
  `idQuiz` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idQuiz`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`QuizScore`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`QuizScore` (
  `score` INT NOT NULL,
  `dateTime` DATETIME NOT NULL,
  `User_login` VARCHAR(32) NOT NULL,
  `Quiz_idQuiz` INT NOT NULL,
  INDEX `fk_QuizScore_User1_idx` (`User_login` ASC),
  INDEX `fk_QuizScore_Quiz1_idx` (`Quiz_idQuiz` ASC),
  PRIMARY KEY (`User_login`, `Quiz_idQuiz`),
  CONSTRAINT `fk_QuizScore_User1`
    FOREIGN KEY (`User_login`)
    REFERENCES `29209262_bd2`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QuizScore_Quiz1`
    FOREIGN KEY (`Quiz_idQuiz`)
    REFERENCES `29209262_bd2`.`Quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Answer` (
  `idAnswer` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`idAnswer`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Question` (
  `idQuestion` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(1024) NOT NULL,
  `rightAnswer_idAnswer` INT NOT NULL,
  PRIMARY KEY (`idQuestion`),
  INDEX `fk_Question_1_idx` (`rightAnswer_idAnswer` ASC),
  CONSTRAINT `fk_Question_1`
    FOREIGN KEY (`rightAnswer_idAnswer`)
    REFERENCES `29209262_bd2`.`Answer` (`idAnswer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Quiz_has_Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Quiz_has_Question` (
  `Question_idQuestion` INT NOT NULL,
  `Quiz_idQuiz` INT NOT NULL,
  INDEX `fk_Question_has_Quiz_Quiz1_idx` (`Quiz_idQuiz` ASC),
  INDEX `fk_Question_has_Quiz_Question1_idx` (`Question_idQuestion` ASC),
  PRIMARY KEY (`Question_idQuestion`, `Quiz_idQuiz`),
  CONSTRAINT `fk_Question_has_Quiz_Question1`
    FOREIGN KEY (`Question_idQuestion`)
    REFERENCES `29209262_bd2`.`Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Question_has_Quiz_Quiz1`
    FOREIGN KEY (`Quiz_idQuiz`)
    REFERENCES `29209262_bd2`.`Quiz` (`idQuiz`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Answer_has_Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Answer_has_Question` (
  `Answer_idAnswer` INT NOT NULL,
  `Question_idQuestion` INT NOT NULL,
  INDEX `fk_Answer_has_Question_Question1_idx` (`Question_idQuestion` ASC),
  INDEX `fk_Answer_has_Question_Answer1_idx` (`Answer_idAnswer` ASC),
  PRIMARY KEY (`Answer_idAnswer`, `Question_idQuestion`),
  CONSTRAINT `fk_Answer_has_Question_Answer1`
    FOREIGN KEY (`Answer_idAnswer`)
    REFERENCES `29209262_bd2`.`Answer` (`idAnswer`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Answer_has_Question_Question1`
    FOREIGN KEY (`Question_idQuestion`)
    REFERENCES `29209262_bd2`.`Question` (`idQuestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Issue`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Issue` (
  `idIssue` INT NOT NULL AUTO_INCREMENT,
  `dateTime` DATETIME NOT NULL,
  `description` VARCHAR(256) NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  `User_login` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`idIssue`),
  INDEX `fk_Issue_Movie1_idx` (`Movie_idMovie` ASC),
  INDEX `fk_Issue_User1_idx` (`User_login` ASC),
  INDEX `date` (`dateTime` ASC),
  CONSTRAINT `fk_Issue_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `29209262_bd2`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Issue_User1`
    FOREIGN KEY (`User_login`)
    REFERENCES `29209262_bd2`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Review` (
  `idReview` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(1024) NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  `User_login` VARCHAR(32) NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`idReview`),
  INDEX `fk_Review_Movie1_idx` (`Movie_idMovie` ASC),
  INDEX `fk_Review_User1_idx` (`User_login` ASC),
  CONSTRAINT `fk_Review_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `29209262_bd2`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Review_User1`
    FOREIGN KEY (`User_login`)
    REFERENCES `29209262_bd2`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Like` (
  `Review_idReview` INT NOT NULL,
  `User_login` VARCHAR(32) NOT NULL,
  `date` DATE NOT NULL,
  INDEX `fk_Like_Review1_idx` (`Review_idReview` ASC),
  INDEX `fk_Like_User1_idx` (`User_login` ASC),
  PRIMARY KEY (`Review_idReview`, `User_login`),
  CONSTRAINT `fk_Like_Review1`
    FOREIGN KEY (`Review_idReview`)
    REFERENCES `29209262_bd2`.`Review` (`idReview`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Like_User1`
    FOREIGN KEY (`User_login`)
    REFERENCES `29209262_bd2`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`ToWatch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`ToWatch` (
  `User_login` VARCHAR(32) NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  INDEX `fk_towatch_User1_idx` (`User_login` ASC),
  INDEX `fk_towatch_Movie1_idx` (`Movie_idMovie` ASC),
  PRIMARY KEY (`User_login`, `Movie_idMovie`),
  CONSTRAINT `fk_towatch_User1`
    FOREIGN KEY (`User_login`)
    REFERENCES `29209262_bd2`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_towatch_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `29209262_bd2`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Movie_has_Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Movie_has_Artist` (
  `Movie_idMovie` INT NOT NULL,
  `Artist_has_ArtistType_id` INT NOT NULL,
  `Role` VARCHAR(45) NULL,
  INDEX `fk_Movie_has_Artist_Movie1_idx` (`Movie_idMovie` ASC),
  INDEX `fk_Movie_has_Artist_1_Artist1_idx` (`Artist_has_ArtistType_id` ASC),
  PRIMARY KEY (`Movie_idMovie`, `Artist_has_ArtistType_id`),
  CONSTRAINT `fk_Movie_has_Artist_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `29209262_bd2`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Movie_has_Artist_1_Artist1`
    FOREIGN KEY (`Artist_has_ArtistType_id`)
    REFERENCES `29209262_bd2`.`Artist_has_ArtistType` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `29209262_bd2`.`Rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `29209262_bd2`.`Rating` (
  `User_login` VARCHAR(32) NOT NULL,
  `Movie_idMovie` INT NOT NULL,
  `rate` INT NOT NULL,
  `date` DATE NOT NULL,
  PRIMARY KEY (`User_login`, `Movie_idMovie`),
  INDEX `fk_User_has_Movie_Movie1_idx` (`Movie_idMovie` ASC),
  INDEX `fk_User_has_Movie_User1_idx` (`User_login` ASC),
  CONSTRAINT `fk_User_has_Movie_User1`
    FOREIGN KEY (`User_login`)
    REFERENCES `29209262_bd2`.`User` (`login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Movie_Movie1`
    FOREIGN KEY (`Movie_idMovie`)
    REFERENCES `29209262_bd2`.`Movie` (`idMovie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
